# Generated by Django 2.1.1 on 2022-02-19 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
                ('descripcion', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=20)),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=70)),
                ('precio_producto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vendedor_id', models.IntegerField()),
                ('cantidades', models.IntegerField()),
            ],
        ),
    ]
