# Generated by Django 2.1.1 on 2022-02-19 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventarioModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=70)),
                ('precio_producto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vendedor_id', models.IntegerField()),
                ('cantidades', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='cantidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(max_length=20),
        ),
    ]
